### ISSUE TITLE
Acronyms are not preserved when title casing CAPS LOCK strings

### ISSUE THREAD

**Issue by verhovsky** [ppannuto/python-titlecase#43]
```python
>>> titlecase("THIS IS A BOOK ABOUT UDP")
'This Is a Book About Udp'
>>> titlecase("this is a book about UDP")
'This Is a Book About UDP'
```

Besides having a list of all things that are probably acronyms (which would never be complete and sometimes depends on context, for example "us" vs "US"), I'm not sure there's anything you can do here. 

It would be good to have a list of some of the things this library can't handle documented in the README.

**Comment by 1kastner** [comment]
Moreover, I would like to maintain my personal abbreviation list somewhere in my home folder.

**Comment by ppannuto** [comment]
I'm open to PRs for any of these. At this point this library is basically maintenance mode for me, I'll fix bugs, but don't really have the development cycles to author new features myself.

I'm wary of documenting a list of 'what is not handled', as it implies everything else is :).

**Comment by 1kastner** [comment]
See #48

**Comment by Polymuter** [comment]
A quick dynamic method would be using something like spaCy.

Example:
```
import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp("THIS IS A BOOK ABOUT UDP")
for token in doc:
    print(token.text, token.pos_, token.dep_)
```
Output:
```
THIS DET nsubj
IS VERB ROOT
A DET det
BOOK NOUN attr
ABOUT ADP prep
UDP NOUN pobj
```

You could then use the process of elimination.  I assume acronyms are always nouns so you now have two words to work with.  The dep_ property is useful but I don't know where to find documentation on it.  I'm not very experienced with spaCy or English grammar.  You could try asking the spaCy guys for help since title capitalization seems like a good use case.

**Comment by 1kastner** [comment]
In my case abbreviations are quite topic-specific so it would not benefit me to use spacy. I guess using spacy would require a complete redevelopment of this module and the way it behaves would be quite different. Maybe you could code it and give it a try?

**Comment by Polymuter** [comment]
I've actually been toying with spaCy to replace titlecase in my code.  I have a working example that can detect more stuff like phrasal verbs, etc.   I was only suggesting he use spaCy as a supplement like I have been doing with nltk for some time now.  Unfortunately, I still think it's better to assume all caps are acronyms since I'm only interested in correcting common errors.  So I wouldn't be interested in adding it.

**Comment by ppannuto** [comment]
I believe this is largely addressed now. Feel free to open PRs for any additional features that may be appropriate.
