### ISSUE TITLE
Wordlist filter feature issues

### ISSUE THREAD

**Issue by ses4j** [ppannuto/python-titlecase#66]
I think there's some optimizations to be made with the new custom wordlist feature.

I upgraded packages wholesale and got a new titlecase.  Out of the box, every time I run my app I get thousands of this message:

    No config file found at C:\Users\user\.titlecase.txt [titlecase:79 create_wordlist_filter]

I can suppress the logging message, but I cannot stop titlecase from looking for a file I know to not be there.  Also, if I DID use this file, it would very inefficiently have to find, open, and read this file upon every titlecase invocation.

So, a couple thoughts:
* The default `titlecase` wordlist_file=None should actually mean there is no wordlist file, rather than for the method to default to a magic filename to check over and over.
* Keep a cache or require the user to just pass a wordlist array from memory, so you don't have to open and read this file repeatedly. If I can just call titlecase with "ignore_words=['FBI', 'CIA', 'NSA']" then we can avoid all the file stuff and it's attendant performance issues and logging noise.
* At a minimum, one way or another I must be able to disable the file loading capability.

**Comment by iburago** [comment]
I believe, I have filed essentially the same issue in #58, which has
been fixed in #60, and will be released soon. (I have a couple of
other minor bug fixes to be filed over the weekend that @ppannuto
kindly agreed to wait on in preparation for the new version.)

As to the in-memory wordlist, the user of the library already can
easily implement that by providing an appropriate callback, like so:

	ignore_words = ['FBI', 'CIA', 'NSA']
	titlecase(str, callback=lambda w: w if w in ignore_words else None)

**Comment by ppannuto** [comment]
I believe @iburago is right. If there's something more that needs to be addressed, feel free to re-open this issue or create a new, more focused one.
